---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# aphylo2

<!-- badges: start -->
<!-- badges: end -->

The goal of aphylo2 is to ...

## Installation

You can install the released version of aphylo2 from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("aphylo2")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("USCbiostats/aphylo2")
```
## Example

```{r simulating-data}
library(aphylo2)

# Preparing data
n <- 100L
annotations <- replicate(n * 2 - 1, c(9, 9), simplify = FALSE)

# Random tree
set.seed(31)
tree <- aphylo::sim_tree(n)$edge - 1L

duplication <- rep(TRUE, n * 2 - 1)

# Reading the data in
amodel <- new_model(
  annotations = annotations,
  geneid = c(tree[, 2], n),
  parent = c(tree[, 1], -1),
  duplication = duplication
  )

# Preparing the model
invisible({
  
  term_gains(amodel, 0:1)
  term_loss(amodel, 0:1)
  term_maxfuns(amodel, 1, 1)
  
  init(amodel)
  
})

# Testing
params <- c(
  # Gains
  2, 1.5,
  # Loss
  -2, -1.5,
  # Max funs
  2, 
  # Root probabilities
  -10, -10
)
names(params) <- c("gain0", "gain1", "loss0", "loss1", "onefun", "root0", "root1")

likelihood(amodel, params*0) # Equals 1 b/c all missings

# Simulating data
fake <- sim_aphylo2(p = amodel, par = params, seed = 1110)
```

```{r mle}
# Fitting the model
fake[101:199] <- replicate(99, c(9L,9L), simplify = FALSE)
amodel <- new_model(
  annotations = fake,
  geneid = tree[, 2],
  parent = tree[, 1],
  duplication = duplication
  )

invisible({
  
  term_gains(amodel, 0:1)
  term_loss(amodel, 0:1)
  term_maxfuns(amodel, 1, 1)
  
  init(amodel)
  
})

# Finding MLE
ans <- aphylo2_mle(amodel, hessian = TRUE)
ans
# [1]  0.6881464  1.0305919 -0.9295311 -1.1126288  1.4606278 -0.1944617 -1.0264741
# Root node probabilities and odds ratios
plogis(tail(ans$par, 2))
exp(ans$par[1:5])

# Is it invertible?
diag(MASS::ginv(-ans$hessian))
# diag(solve(-ans$hessian, tol = 1e-100))

```


```{r mcmc-fit, cache=TRUE}
set.seed(122)
ans_mcmc <- aphylo2_mcmc(
  amodel,
  nsteps  = 20000,
  kernel  = fmcmc::kernel_ram(warmup = 2000), 
  prior   = function(p) dlogis(p, scale = 2, log = TRUE)
  )
```

```{r mcmc-analysis}
op <- par(mfrow = c(4, 2))
for (i in 1:ncol(ans_mcmc)) {
  tmpx <- window(ans_mcmc, start = 15000)[,i,drop=FALSE]
  plot(
    density(tmpx),
    main = names(params)[i]
    )
  abline(v = quantile(tmpx, .5), lty = 2, lwd = 2, col = "tomato")
  abline(v = params[i], lty=3, lwd=2, col = "steelblue")
}
par(op)
summary(window(ans_mcmc, start = 15000))
```



## Code of Conduct
  
Please note that the aphylo2 project is released with a [Contributor Code of Conduct](https://contributor-covenant.org/version/2/0/CODE_OF_CONDUCT.html). By contributing to this project, you agree to abide by its terms.
