# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Flock of GEESE
#' @description Flocks are pooled models which include multiple phylums.
#' @name flock-class
#' @export
#' @aliases flock
new_flock <- function() {
    .Call(`_geese_new_flock`)
}

#' @rdname flock-class
#' @param p An object of class `flock`.
#' @param annotations Vector of integer vectors with annotations.
#' @param geneid integer vector with gene ids
#' @param parent integer vector with parent gene id
#' @export
add_geese <- function(p, annotations, geneid, parent, duplication) {
    invisible(.Call(`_geese_add_geese`, p, annotations, geneid, parent, duplication))
}

#' @title Common functions for `geese` and `flock`.
#' @name geese-common
#' @param p An object of class [geese] or [flock].
#' @export
#' @aliases flock-common
#' @details `init_model` initializes the model. This triggers the calculation
#' of the support using the vector of terms included. Initializing a model can
#' only be done once.
init_model <- function(p) {
    invisible(.Call(`_geese_init_model`, p))
}

#' @rdname geese-common
#' @export
#' @returns `nterms` returns the number of terms included in the model. This
#' is different from the number of parameters as the later includes the number
#' of functions in the data.
nterms <- function(p) {
    .Call(`_geese_nterms`, p)
}

#' @rdname geese-common
#' @returns `nnodes` returns the number of nodes in the data, this includes
#' internal nodes. If `p` is a [flock], then it will return a vector of length
#' `ntrees()`.
#' @export
nnodes <- function(p) {
    .Call(`_geese_nnodes`, p)
}

#' @rdname geese-common
#' @returns `ntrees` returns the number of trees in the model. For a geese object
#' this will be equal to one.
#' @export
ntrees <- function(p) {
    .Call(`_geese_ntrees`, p)
}

#' @rdname geese-common
#' @export
nleafs <- function(p) {
    .Call(`_geese_nleafs`, p)
}

#' @rdname geese-common
#' @export
#' @param par Numeric vector of length `nterms()`.
#' @param trunc_seq When `TRUE` uses the truncated pruning sequence (see details).
#' @details Using the truncated pruning sequence (`trunc_seq = TRUE`) involves
#' traversing the trees throught the induced subtree. This is relevant in the case
#' that not all the leafs are annotated.
likelihood <- function(p, par, as_log = FALSE, trunc_seq = TRUE) {
    .Call(`_geese_likelihood`, p, par, as_log, trunc_seq)
}

#' @rdname geese-common
#' @export
get_probabilities <- function(p) {
    .Call(`_geese_get_probabilities`, p)
}

#' @rdname geese-common
#' @export
get_sequence <- function(p, reduced_sequence = TRUE) {
    .Call(`_geese_get_sequence`, p, reduced_sequence)
}

#' @rdname geese-common
#' @export
set_seed <- function(p, s) {
    invisible(.Call(`_geese_set_seed`, p, s))
}

#' @rdname geese-common
#' @export
sim_geese <- function(p, par, seed = -1L) {
    .Call(`_geese_sim_geese`, p, par, seed)
}

#' @rdname geese-common
#' @export
observed_counts <- function(p) {
    .Call(`_geese_observed_counts`, p)
}

#' @rdname geese-common
#' @export
print_observed_counts <- function(p) {
    invisible(.Call(`_geese_print_observed_counts`, p))
}

#' @title Evolutionary terms
#' @description Model terms for both [geese] and [flock] objects.
#' @export
#' @param p An object of class [geese] or [flock].
#' @param funs Vector of function indices (starting from zero).
#' @param duplication When `TRUE` indicates that this term is only valid for
#' duplication events.
#' @name geese-terms
rule_limit_changes <- function(p, term_pos, lb, ub, duplication = TRUE) {
    invisible(.Call(`_geese_rule_limit_changes`, p, term_pos, lb, ub, duplication))
}

#' @export
#' @rdname geese-common
predict_geese <- function(p, par, leave_one_out = FALSE, use_reduced_sequence = TRUE, only_annotated = FALSE) {
    .Call(`_geese_predict_geese`, p, par, leave_one_out, use_reduced_sequence, only_annotated)
}

#' @export
#' @rdname geese-common
predict_flock <- function(p, par, leave_one_out = FALSE, use_reduced_sequence = TRUE, only_annotated = FALSE) {
    .Call(`_geese_predict_flock`, p, par, leave_one_out, use_reduced_sequence, only_annotated)
}

#' @title Evolutionary terms
#' @description Model terms for both [geese] and [flock] objects.
#' @export
#' @param p An object of class [geese] or [flock].
#' @param funs Vector of function indices (starting from zero).
#' @param duplication When `TRUE` indicates that this term is only valid for
#' duplication events.
#' @name geese-terms
term_gains <- function(p, funs, duplication = TRUE) {
    invisible(.Call(`_geese_term_gains`, p, funs, duplication))
}

#' @export
#' @rdname geese-terms
term_loss <- function(p, funs, duplication = TRUE) {
    invisible(.Call(`_geese_term_loss`, p, funs, duplication))
}

#' @export
#' @rdname geese-terms
#' @param a,b Indices of functions (starting from zero)
term_cogain <- function(p, a, b) {
    invisible(.Call(`_geese_term_cogain`, p, a, b))
}

#' @export
#' @rdname geese-terms
term_neofun <- function(p, a, b) {
    invisible(.Call(`_geese_term_neofun`, p, a, b))
}

#' @export
#' @rdname geese-terms
term_subfun <- function(p, a, b) {
    invisible(.Call(`_geese_term_subfun`, p, a, b))
}

#' @export
#' @rdname geese-terms
#' @oarams lb,ub Integers, minimum and maximum number of changes.
term_maxfuns <- function(p, lb, ub, duplication = TRUE) {
    invisible(.Call(`_geese_term_maxfuns`, p, lb, ub, duplication))
}

#' @export
#' @rdname geese-terms
term_overall_changes <- function(p, duplication = TRUE) {
    invisible(.Call(`_geese_term_overall_changes`, p, duplication))
}

#' @export
#' @rdname geese-terms
term_kgains <- function(p, funs, k = 1L, duplication = TRUE) {
    invisible(.Call(`_geese_term_kgains`, p, funs, k, duplication))
}

#' @export
#' @rdname geese-terms
#' @details In the case of `term_neofun_a2b`, `a` represents the origin function
#' from which `b` is originated.
term_neofun_a2b <- function(p, a, b, duplication = TRUE) {
    invisible(.Call(`_geese_term_neofun_a2b`, p, a, b, duplication))
}

#' @export
#' @rdname geese-terms
term_genes_changing <- function(p, duplication = TRUE) {
    invisible(.Call(`_geese_term_genes_changing`, p, duplication))
}

#' @export
#' @rdname geese-terms
term_coopt <- function(p, a, b, duplication = TRUE) {
    invisible(.Call(`_geese_term_coopt`, p, a, b, duplication))
}

#' @title GEne Evolutionary model using SufficiEncy (GEESE)
#' @name geese-class
#' @param p An object of class `geese`.
#' @param annotations Vector of integer vectors with annotations.
#' @param geneid integer vector with gene ids
#' @param parent integer vector with parent gene id
#' @export
#' @aliases geese
new_geese <- function(annotations, geneid, parent, duplication) {
    .Call(`_geese_new_geese`, annotations, geneid, parent, duplication)
}

