# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Aphylo2 model
#' @name aphylo2-class
#' @param annotations Vector of integer vectors with annotations.
#' @param geneid integer vector with gene ids
#' @param parent integer vector with parent gene id
#' @export
new_model <- function(annotations, geneid, parent, duplication) {
    .Call(`_aphylo2_new_model`, annotations, geneid, parent, duplication)
}

#' @rdname aphylo2-class
#' @export
init <- function(p) {
    .Call(`_aphylo2_init`, p)
}

#' @rdname aphylo2-class
#' @export
nterms <- function(p) {
    .Call(`_aphylo2_nterms`, p)
}

#' @rdname aphylo2-class
#' @export
nnodes <- function(p) {
    .Call(`_aphylo2_nnodes`, p)
}

#' @rdname aphylo2-class
#' @export
nleafs <- function(p) {
    .Call(`_aphylo2_nleafs`, p)
}

#' @rdname aphylo2-class
#' @export
likelihood <- function(p, par) {
    .Call(`_aphylo2_likelihood`, p, par)
}

#' @rdname aphylo2-class
#' @export
get_probabilities <- function(p) {
    .Call(`_aphylo2_get_probabilities`, p)
}

#' @rdname aphylo2-class
#' @export
get_sequence <- function(p) {
    .Call(`_aphylo2_get_sequence`, p)
}

#' @rdname aphylo2-class
#' @export
set_seed <- function(p, s) {
    .Call(`_aphylo2_set_seed`, p, s)
}

#' @rdname aphylo2-class
#' @export
sim_aphylo2 <- function(p, par, seed = -1L) {
    .Call(`_aphylo2_sim_aphylo2`, p, par, seed)
}

#' @rdname aphylo2-class
#' @export
observed_counts <- function(p) {
    .Call(`_aphylo2_observed_counts`, p)
}

#' @rdname aphylo2-class
#' @export
print_observed_counts <- function(p) {
    .Call(`_aphylo2_print_observed_counts`, p)
}

#' @title Evolutionary terms
#' @export
#' @name aphylo2-terms
term_gains <- function(p, funs, duplication = TRUE) {
    .Call(`_aphylo2_term_gains`, p, funs, duplication)
}

#' @export
#' @rdname aphylo2-terms
term_loss <- function(p, funs, duplication = TRUE) {
    .Call(`_aphylo2_term_loss`, p, funs, duplication)
}

#' @export
#' @rdname aphylo2-terms
term_cogain <- function(p, a, b) {
    .Call(`_aphylo2_term_cogain`, p, a, b)
}

#' @export
#' @rdname aphylo2-terms
term_neofun <- function(p, a, b) {
    .Call(`_aphylo2_term_neofun`, p, a, b)
}

#' @export
#' @rdname aphylo2-terms
term_subfun <- function(p, a, b) {
    .Call(`_aphylo2_term_subfun`, p, a, b)
}

#' @export
#' @rdname aphylo2-terms
term_maxfuns <- function(p, lb, ub) {
    .Call(`_aphylo2_term_maxfuns`, p, lb, ub)
}

#' @export
#' @rdname aphylo2-terms
term_overall_changes <- function(p, duplication = TRUE) {
    .Call(`_aphylo2_term_overall_changes`, p, duplication)
}

#' @export
#' @rdname aphylo2-terms
term_kgains <- function(p, funs, k = 1L, duplication = TRUE) {
    .Call(`_aphylo2_term_kgains`, p, funs, k, duplication)
}

