# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Aphylo2 model
#' @name aphylo2-class
#' @param annotations Vector of integer vectors with annotations.
#' @param geneid integer vector with gene ids
#' @param parent integer vector with parent gene id
#' @export
new_model <- function(annotations, geneid, parent) {
    .Call(`_aphylo2_new_model`, annotations, geneid, parent)
}

#' @rdname aphylo2-class
#' @export
init <- function(p) {
    .Call(`_aphylo2_init`, p)
}

#' @rdname aphylo2-class
#' @export
likelihood <- function(p, par) {
    .Call(`_aphylo2_likelihood`, p, par)
}

#' @title Evolutionary terms
#' @export
#' @name aphylo2-terms
term_gains <- function(p, funs) {
    .Call(`_aphylo2_term_gains`, p, funs)
}

#' @export
#' @rdname aphylo2-terms
term_loss <- function(p, funs) {
    .Call(`_aphylo2_term_loss`, p, funs)
}

#' @export
#' @rdname aphylo2-terms
term_cogain <- function(p, a, b) {
    .Call(`_aphylo2_term_cogain`, p, a, b)
}

#' @export
#' @rdname aphylo2-terms
term_neofun <- function(p, a, b) {
    .Call(`_aphylo2_term_neofun`, p, a, b)
}

#' @export
#' @rdname aphylo2-terms
term_subfun <- function(p, a, b) {
    .Call(`_aphylo2_term_subfun`, p, a, b)
}

